### PR TITLE
Solve Problem 78. Subsets in C Language

### PR DESCRIPTION
**Pull request by Rejwan321**
I had solved the problem on leetcode and run it. Please check it out and see if I need to make any changes.

### CODE REVIEW

**Comment by threeal** [comment]
Hi @Rejwan321, thanks for the contribution. Can you also make the following changes:
- Fix formatting by running `clang-format -i old-problems/0078/c/solution.c`.
- Update the `CMakeLists.txt` file, add an `interface.cpp` file, and try building and testing the solution locally.
- Update the `README.md` file.

You can also refer to #682 for the changes I usually make to add a C solution.

**Comment by Rejwan321** [comment]
Okk I will check it out

**Comment by Rejwan321** [comment]
All right almost everything done, except the fix formatting part, I don't know if it's a glitch or not but I tried running it on vs code it didn't work

**Comment by Rejwan321** [comment]
Alright I have made all the changes you have asked for, except I couldn't fix formatting using my local compiler somehow `clang-format  -i` didn't work on my pc. Please check it out, and tell me if something needs to be fixed.

**Comment by Rejwan321** [comment]
alright, ill check and fix these errors. Please wait for a while

**Comment by Rejwan321** [comment]
Please check if there are any more errors.

**Pull request closed without merging**
